project:
  anaconda_path: 
  protein_file: ./example/ggtdt_af3.cif
  output_dir: ./ggtdt_example
  chain: A
  sequence_length: 386
  segment: 8-22  # 如果为None则只执行profile部分分析，不跑后续设计

profile:
  database: ./database/ggtdt_af3_A_homologous_sequences.fasta
  bitscore: 0.3
  n_iter: 5
  cpu: 10
  threshold: 0.6

rfdiffusion:
  helix: True
  strand: 
  num_designs: 10
  threshold: 0.5

mpnn:
  num_seq_per_target: 20
  sampling_temp: 0.2
  batch_size: 5
  seed: 42
  top_percent: 0.5

mmseqs:
  min_seq_id: 0.8
  s: 7.5
  c: 1.0

esmfold:
  ptm_threshold: 0.54
  plddt_threshold: 70
  #ss: helix
  #ss_threshold: 0.3

alphafold2:
  ptm_threshold: 0.54
  plddt_threshold: 70
  #ss: helix
  #ss_threshold: 0.3
   
