# 模块配置
environments:
  main_env: segdesign
  hmmer: 
  rfdiffusion: segdesign_SE3nv
  rfdiffusion_report: 
  mpnn: segdesign_SE3nv
  mpnn_report: 
  dssp: 
  mmseqs: 
  esmfold: esmfold
  esmfold_report: 
  alphafold2: segdesign_colabfold


# 模块默认参数
hmmer:
  args:
    output_folder: hmmer_out
    minimum_sequence_coverage: 50
    minimum_column_coverage: 70
    identity: 0.3
    

rfdiffusion:
  args:
    #dssp_analyse:
         #- yes
    run_inference_path: ./RFdiffusion/scripts/run_inference.py
    output_folder: rfdiffusion_out
    diffuser.partial_T: 50
    
mpnn:
  args:
    parse_multiple_chains_path: "./ProteinMPNN/helper_scripts/parse_multiple_chains.py"
    assign_fixed_chains_path: "./ProteinMPNN/helper_scripts/assign_fixed_chains.py"
    make_fixed_positions_dict_path: "./ProteinMPNN/helper_scripts/make_fixed_positions_dict.py"
    protein_mpnn_run_path: "./ProteinMPNN/protein_mpnn_run.py"
    pdb_folder: 
    output_folder: mpnn_out
    top_percent: 0.5
    rfdiffusion_report_path:   #rfdiffusion_report.csv的路径，若不输入则使用默认路径

mmseqs:
  args:
    threads: 8
    min_seq_id: 0.8
    cov_mode: 0
    coverage: 0.8
    mmseqs_path: mmseqs
    sensitivity: 4.0
    output_folder: mmseqs_out

dssp:
  args:
    output_folder: dssp_out


esmfold:
  args:
    output_folder: esmfold_out
    original_protein_chain_path: 
    seq_range_str: 

alphafold2:
  args:
    output_folder: alphafold2_out
    num_recycle: 3 
    amber: True
    templates: True
    gpu: True
    random_seed: 0 


